tasks:
  - before: |
      sudo apt-get update
      sudo apt-get install --assume-yes libgl1
    init: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --requirement requirements.txt
    command: python main.py

vscode:
  extensions:
    - ms-python.python
